spring:
  application:
    name: backend
  
  # PostgreSQL Database Configuration (Render will provide DATABASE_URL)
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  # JPA/Hibernate Configuration for PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

# Logging (reduced for production)
logging:
  level:
    com.smarthome.backend: INFO
    org.springframework.web: WARN
    org.hibernate: WARN

# JWT Configuration (use environment variable in production)
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

# Server configuration
server:
  port: ${PORT:8080}