spring:
  application:
    name: backend
  
  profiles:
    active: dev
  
  # H2 Database Configuration (for local development)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console (for debugging/viewing data)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    com.smarthome.backend: DEBUG
    org.springframework.web: DEBUG

# JWT Configuration
app:
  jwt:
    secret: myVerySecretKeyForJWTTokenGenerationThatIsLongEnoughForSecurity
    expiration: 86400000