version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - gradle-cache:/home/vscode/.gradle
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - GRADLE_USER_HOME=/home/vscode/.gradle
    working_dir: /workspace
    command: sleep infinity
    user: vscode

volumes:
  gradle-cache: